
export const PRODUCTS_URL = 'https://real-time-amazon-data.p.rapidapi.com/products-by-category?category_id=2478868012&page=1&country=US&sort_by=RELEVANCE&product_condition=ALL';

export const Indata = {
    "status": "OK",
    "request_id": "ceb75660-dbad-4d0c-a30e-f81bcf3e01bf",
    "parameters": {
        "category_id": "2478868012",
        "country": "IN",
        "sort_by": "RELEVANCE",
        "page": 1
    },
    "data": {
        "total_products": 793742,
        "country": "IN",
        "domain": "www.amazon.in",
        "products": [
            {
                "asin": "B0D1R4798D",
                "product_title": "Jiotv+",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.6",
                "product_num_ratings": 29,
                "product_url": "https://www.amazon.in/dp/B0D1R4798D",
                "product_photo": "https://m.media-amazon.com/images/I/31GngoiH5pL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "12 June 2024",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B0CWPMW29Y",
                "product_title": "PT Sir",
                "product_price": "₹279",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 2,
                "product_url": "https://www.amazon.in/dp/B0CWPMW29Y",
                "product_photo": "https://m.media-amazon.com/images/I/819PwawtJ6L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹279",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2024",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B0D51NFQ4L",
                "product_title": "Garudan",
                "product_price": "₹279",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B0D51NFQ4L",
                "product_photo": "https://m.media-amazon.com/images/I/A1L8ef4t8NL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹279",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2024",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B0CVD7LHNN",
                "product_title": "Tomb Runner",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.6",
                "product_num_ratings": 253,
                "product_url": "https://www.amazon.in/dp/B0CVD7LHNN",
                "product_photo": "https://m.media-amazon.com/images/I/81jV5YG9pzL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "12 February 2024",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B06XP3HSPW",
                "product_title": "Sony LIV",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.1",
                "product_num_ratings": 26131,
                "product_url": "https://www.amazon.in/dp/B06XP3HSPW",
                "product_photo": "https://m.media-amazon.com/images/I/61JxXK7hNDL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "17 March 2017",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B09JKMSLP4",
                "product_title": "FanCode: Live Cricket, Highlights &amp; Videos",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.6",
                "product_num_ratings": 2641,
                "product_url": "https://www.amazon.in/dp/B09JKMSLP4",
                "product_photo": "https://m.media-amazon.com/images/I/21K+HipHr6L._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "20 October 2021",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B0D362Q811",
                "product_title": "Maidaan",
                "product_price": "₹279",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.2",
                "product_num_ratings": 93,
                "product_url": "https://www.amazon.in/dp/B0D362Q811",
                "product_photo": "https://m.media-amazon.com/images/I/81Q7Sg39TrL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹279",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2024",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B0D3WQGYS3",
                "product_title": "Sharmajee Ki Beti",
                "product_price": "₹279",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "5",
                "product_num_ratings": 1,
                "product_url": "https://www.amazon.in/dp/B0D3WQGYS3",
                "product_photo": "https://m.media-amazon.com/images/I/91R6R34-LlL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹279",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2024",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B0CXH8RL16",
                "product_title": "SATYABHAMA",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B0CXH8RL16",
                "product_photo": "https://m.media-amazon.com/images/I/613ev41uo7L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2024",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B087G5BN7Z",
                "product_title": "discovery+ | TV Shows, Shorts, Fun Learning",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.1",
                "product_num_ratings": 48697,
                "product_url": "https://www.amazon.in/dp/B087G5BN7Z",
                "product_photo": "https://m.media-amazon.com/images/I/71UCyJsuqfL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "4 June 2020",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B071KD377K",
                "product_title": "JioCinema-Shows, Movies &amp; More",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.6",
                "product_num_ratings": 52412,
                "product_url": "https://www.amazon.in/dp/B071KD377K",
                "product_photo": "https://m.media-amazon.com/images/I/31LNEBVsjUL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "15 June 2017",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B0BZVZYXV5",
                "product_title": "SJeware 12 Pairs Solid Cotton Ankle Length Socks for Men &amp; Women, Multicolor, Pack of 12, Free Size",
                "product_price": "₹198",
                "product_original_price": "₹1,299",
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 7411,
                "product_url": "https://www.amazon.in/dp/B0BZVZYXV5",
                "product_photo": "https://m.media-amazon.com/images/I/81TRdxk1wnL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹198",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "20K+ bought in past month",
                "delivery": "FREE Delivery over ₹499. Fulfilled by Amazon",
                "has_variations": false
            },
            {
                "asin": "B086ZJNK5R",
                "product_title": "என் ஜென்மம் ஈடேற வா: En jenmam eedera vaa (Tamil Edition)",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.2",
                "product_num_ratings": 135,
                "product_url": "https://www.amazon.in/dp/B086ZJNK5R",
                "product_photo": "https://m.media-amazon.com/images/I/71FUe5OjaPL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Tamil Edition",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B079PZHHBS",
                "product_title": "ZEE5 Movies Shows LIVE TV Originals",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.2",
                "product_num_ratings": 75011,
                "product_url": "https://www.amazon.in/dp/B079PZHHBS",
                "product_photo": "https://m.media-amazon.com/images/I/51CNksbNcfL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "1 March 2018",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B0D3QVC5QZ",
                "product_title": "Mirzapur - Season 3",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B0D3QVC5QZ",
                "product_photo": "https://m.media-amazon.com/images/I/91+Dkxpd-dL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2024",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B06Y18MPK7",
                "product_title": "Hotstar",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.4",
                "product_num_ratings": 43540,
                "product_url": "https://www.amazon.in/dp/B06Y18MPK7",
                "product_photo": "https://m.media-amazon.com/images/I/71G-63tiCOL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "18 April 2017",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B08JGRH9FY",
                "product_title": "Mirzapur - Season 2",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B08JGRH9FY",
                "product_photo": "https://m.media-amazon.com/images/I/91udUUcgDVL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2020",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B07KX363ZT",
                "product_title": "Aaj Tak - Smart TV App",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 22896,
                "product_url": "https://www.amazon.in/dp/B07KX363ZT",
                "product_photo": "https://m.media-amazon.com/images/I/51QUUmk0znL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "5 December 2018",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B07T1LWHYG",
                "product_title": "MX Player TV",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.1",
                "product_num_ratings": 66642,
                "product_url": "https://www.amazon.in/dp/B07T1LWHYG",
                "product_photo": "https://m.media-amazon.com/images/I/515+F2vlqtL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "17 June 2019",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B072814ZX5",
                "product_title": "Sun NXT",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 23416,
                "product_url": "https://www.amazon.in/dp/B072814ZX5",
                "product_photo": "https://m.media-amazon.com/images/I/61w5YbybBiL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "9 June 2017",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B00OGRMULA",
                "product_title": "Netflix",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.3",
                "product_num_ratings": 91593,
                "product_url": "https://www.amazon.in/dp/B00OGRMULA",
                "product_photo": "https://m.media-amazon.com/images/I/51LGj5--KsL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "15 October 2014",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B081QLMVD7",
                "product_title": "தீயாய் நீ வா : theeyaai nee vaa (Tamil Edition)",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.4",
                "product_num_ratings": 344,
                "product_url": "https://www.amazon.in/dp/B081QLMVD7",
                "product_photo": "https://m.media-amazon.com/images/I/81fbB+SHJ-L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Tamil Edition",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B00CSR2J9I",
                "product_title": "Hill Climb Racing",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 109560,
                "product_url": "https://www.amazon.in/dp/B00CSR2J9I",
                "product_photo": "https://m.media-amazon.com/images/I/71SK1+HcvBL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "16 May 2013",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B07MJV4GVV",
                "product_title": "Mirzapur - Season 1",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": "3",
                "product_num_ratings": 2,
                "product_url": "https://www.amazon.in/dp/B07MJV4GVV",
                "product_photo": "https://m.media-amazon.com/images/I/81bX4exiFOL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2018",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B0D5PQLF96",
                "product_title": "Civil War",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B0D5PQLF96",
                "product_photo": "https://m.media-amazon.com/images/I/915xRqkn9WL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2024",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B076X8FKXP",
                "product_title": "Fawesome - Free Awesome TV &amp; Movies",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 52670,
                "product_url": "https://www.amazon.in/dp/B076X8FKXP",
                "product_photo": "https://m.media-amazon.com/images/I/81VLg+9NcRL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "28 October 2017",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B08CKPSHLL",
                "product_title": "Xstream Play",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.7",
                "product_num_ratings": 30424,
                "product_url": "https://www.amazon.in/dp/B08CKPSHLL",
                "product_photo": "https://m.media-amazon.com/images/I/71JqJwLEvUL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "17 September 2020",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B08JPDLL1Z",
                "product_title": "Free Movies Plus",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.5",
                "product_num_ratings": 52278,
                "product_url": "https://www.amazon.in/dp/B08JPDLL1Z",
                "product_photo": "https://m.media-amazon.com/images/I/61BlTnHAwTL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "22 September 2020",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B09YV13JQG",
                "product_title": "Panchayat - Season 2",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B09YV13JQG",
                "product_photo": "https://m.media-amazon.com/images/I/81NATxFbIVL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2022",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B0D29P1WS6",
                "product_title": "Panchayat - Season 3",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B0D29P1WS6",
                "product_photo": "https://m.media-amazon.com/images/I/91VBeOucwIL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2024",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B083GXWFDM",
                "product_title": "இனம் புரியா உறவிதுவோ : Inam puriyaa uravithuvo (Tamil Edition)",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.2",
                "product_num_ratings": 134,
                "product_url": "https://www.amazon.in/dp/B083GXWFDM",
                "product_photo": "https://m.media-amazon.com/images/I/81q26x89gYL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Tamil Edition",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B07BG5GZP2",
                "product_title": "Fresh Potato, 1kg",
                "product_price": "₹52",
                "unit_price": "₹5.20",
                "unit_count": 10,
                "product_original_price": "₹64",
                "currency": "INR",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B07BG5GZP2",
                "product_photo": "https://m.media-amazon.com/images/I/313dtY-LOEL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹52",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "1L+ bought in past month",
                "delivery": "FREE delivery starting from as soon as Wed, 17 Jul, 7 am - 11 am on orders over ₹499",
                "has_variations": false
            },
            {
                "asin": "B01N0BP507",
                "product_title": "Downloader",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.8",
                "product_num_ratings": 658209,
                "product_url": "https://www.amazon.in/dp/B01N0BP507",
                "product_photo": "https://m.media-amazon.com/images/I/31CQo-EeuTL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "11 November 2016",
                "delivery": "Available for download now",
                "has_variations": false
            },
            {
                "asin": "B08CRLVYJL",
                "product_title": "The Boys – Season 2",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B08CRLVYJL",
                "product_photo": "https://m.media-amazon.com/images/I/915pQr7zq-L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2020",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B086PDGCFM",
                "product_title": "Panchayat - Season 1",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B086PDGCFM",
                "product_photo": "https://m.media-amazon.com/images/I/81SnS9vo-ML._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2020",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B0CLWYJF1Q",
                "product_title": "The Boys – Season 4",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B0CLWYJF1Q",
                "product_photo": "https://m.media-amazon.com/images/I/81McDLT3uYL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2024",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B0D96P6TPG",
                "product_title": "பெருங்காமமாகி காதலுருகிறேன் (Tamil Edition)",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.5",
                "product_num_ratings": 79,
                "product_url": "https://www.amazon.in/dp/B0D96P6TPG",
                "product_photo": "https://m.media-amazon.com/images/I/616leKvRfIL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Tamil Edition",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0D8QB4PJH",
                "product_title": "STRATIZE Waterproof Shoe Covers Reusable Silicone Cover Shoes Rain Boots for Men, Women, Kids |Overshoes Protectors for Kitchen, Indoor,Outdoor",
                "product_price": "₹299",
                "product_original_price": "₹999",
                "currency": "INR",
                "product_star_rating": "4.5",
                "product_num_ratings": 54,
                "product_url": "https://www.amazon.in/dp/B0D8QB4PJH",
                "product_photo": "https://m.media-amazon.com/images/I/41IMkQ12xbL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹299",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "800+ bought in past month",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B07BG62MBV",
                "product_title": "Fresh Onion, 1kg",
                "product_price": "₹48",
                "unit_price": "₹4.80",
                "unit_count": 10,
                "product_original_price": "₹67",
                "currency": "INR",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B07BG62MBV",
                "product_photo": "https://m.media-amazon.com/images/I/51DJ-9xkuQL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹48",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "1L+ bought in past month",
                "delivery": "FREE delivery starting from as soon as Tue, 16 Jul, 8 am - 12 pm on orders over ₹499",
                "has_variations": false
            },
            {
                "asin": "B0D98PQ89D",
                "product_title": "தித்திக்கும் தீஞ்சுவையே!! (Tamil Edition)",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.8",
                "product_num_ratings": 28,
                "product_url": "https://www.amazon.in/dp/B0D98PQ89D",
                "product_photo": "https://m.media-amazon.com/images/I/61EbCoq9oaL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Tamil Edition",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B07QSFCRLC",
                "product_title": "The Boys - Season 1",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B07QSFCRLC",
                "product_photo": "https://m.media-amazon.com/images/I/A1ISB4F5kRL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2019",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B07XJR6KJB",
                "product_title": "விழிகள் தேடும் மொழிகள்: Vilikal Thedum Molikal (Tamil Edition)",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.2",
                "product_num_ratings": 371,
                "product_url": "https://www.amazon.in/dp/B07XJR6KJB",
                "product_photo": "https://m.media-amazon.com/images/I/715n7lO9hyL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Tamil Edition",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0D8T78KQQ",
                "product_title": "Fargo Leatherette Side White Sling Bags For Women&#x27;s Ladies",
                "product_price": "₹199",
                "product_original_price": "₹999",
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 1,
                "product_url": "https://www.amazon.in/dp/B0D8T78KQQ",
                "product_photo": "https://m.media-amazon.com/images/I/31AwRxzgq1L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹199",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "1K+ bought in past month",
                "delivery": "FREE Delivery over ₹499. Fulfilled by Amazon",
                "has_variations": false
            },
            {
                "asin": "B07WQM6MKB",
                "product_title": "யாவும் காதல் செய்த மாயம் பாகம் 2: Yaavum Kathal seitha maayam II (Tamil Edition)",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.3",
                "product_num_ratings": 242,
                "product_url": "https://www.amazon.in/dp/B07WQM6MKB",
                "product_photo": "https://m.media-amazon.com/images/I/81QcGwnN0WL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Tamil Edition",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0D814GNXK",
                "product_title": "Fargo Leatherette Side Black Sling Bags For Women&#x27;s Ladies",
                "product_price": "₹199",
                "product_original_price": "₹1,999",
                "currency": "INR",
                "product_star_rating": "2.5",
                "product_num_ratings": 23,
                "product_url": "https://www.amazon.in/dp/B0D814GNXK",
                "product_photo": "https://m.media-amazon.com/images/I/612WOnKLLML._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹199",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE Delivery over ₹499. Fulfilled by Amazon",
                "has_variations": false
            },
            {
                "asin": "B0D6K1Z3QF",
                "product_title": "நெஞ்சில் விழுந்த நேசவிதையே... (Tamil Edition)",
                "product_price": "₹0",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.1",
                "product_num_ratings": 26,
                "product_url": "https://www.amazon.in/dp/B0D6K1Z3QF",
                "product_photo": "https://m.media-amazon.com/images/I/71K0zn0AZ7L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹0",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Tamil Edition",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0CY532CH5",
                "product_title": "My Lady Jane - Season 1",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.in/dp/B0CY532CH5",
                "product_photo": "https://m.media-amazon.com/images/I/91Jjx3xLaRL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": null,
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "2024",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B01LWYDEQ7",
                "product_title": "Pigeon Polypropylene Mini Handy and Compact Chopper with 3 Blades for Effortlessly Chopping Vegetables and Fruits for Your Kitchen (12420, Green, 400 ml)",
                "product_price": "₹151",
                "product_original_price": "₹495",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 256804,
                "product_url": "https://www.amazon.in/dp/B01LWYDEQ7",
                "product_photo": "https://m.media-amazon.com/images/I/51RXzjrUmkL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹151",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "Get it by Tomorrow, 15 JulyFREE Delivery over ₹499. Fulfilled by Amazon",
                "has_variations": false
            }
        ]
    }
}

export const data = {
    "status": "OK",
    "request_id": "4c9a3bdf-a7ac-4311-a5c8-6219c9b495b2",
    "parameters": {
        "category_id": "2478868012",
        "country": "US",
        "sort_by": "RELEVANCE",
        "page": 1
    },
    "data": {
        "total_products": 992468,
        "country": "US",
        "domain": "www.amazon.com",
        "products": [
            {
                "asin": "B0CWXNS552",
                "product_title": "Apple AirTag",
                "product_price": "$24.00",
                "product_original_price": "$29.00",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 2661,
                "product_url": "https://www.amazon.com/dp/B0CWXNS552",
                "product_photo": "https://m.media-amazon.com/images/I/71rP7f78eFL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 4,
                "product_minimum_offer_price": "$23.04",
                "is_best_seller": false,
                "is_amazon_choice": true,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery on $35 shipped by Amazon.",
                "has_variations": false
            },
            {
                "asin": "1649374186",
                "product_title": "Onyx Storm (Deluxe Limited Edition) (The Empyrean, 3)",
                "product_price": "$19.78",
                "product_original_price": "$32.99",
                "currency": "USD",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.com/dp/1649374186",
                "product_photo": "https://m.media-amazon.com/images/I/9101MLPcFTL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$19.78",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "List: ",
                "delivery": "FREE delivery Mon, Jan 27, 2025 on $35 of items shipped by AmazonOr fastest delivery Tue, Jan 21, 2025 This title will be released on January 21, 2025.",
                "has_variations": false
            },
            {
                "asin": "B0D5FZGY8W",
                "product_title": "URO Vaginal Probiotics for Women pH Balance with Prebiotics &amp; Lactobacillus Probiotic Blend - Women&#x27;s Vaginal Health Supplement - Promote Healthy Vaginal Odor &amp; Vaginal Flora, 60 Count (Pack of 1)",
                "product_price": "$28.79",
                "unit_price": "$0.48",
                "unit_count": 60,
                "product_original_price": "$31.99",
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 577,
                "product_url": "https://www.amazon.com/dp/B0D5FZGY8W",
                "product_photo": "https://m.media-amazon.com/images/I/61tYAHJi3LL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$28.79",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "100K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0D92TH7MV",
                "product_title": "Keep It Simple Y&#x27;all: Easy dinners from Your Barefoot Neighbor",
                "product_price": null,
                "product_original_price": null,
                "currency": null,
                "product_star_rating": "4.9",
                "product_num_ratings": 77,
                "product_url": "https://www.amazon.com/dp/B0D92TH7MV",
                "product_photo": "https://m.media-amazon.com/images/I/61Zk8idxPKL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$39.99",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "No featured offers available",
                "delivery": null,
                "has_variations": false
            },
            {
                "asin": "B0CV4FQPY1",
                "product_title": "Bounty Select-A-Size Paper Towels, White, 8 Triple Rolls = 24 Regular Rolls",
                "product_price": "$22.18",
                "unit_price": "$2.05",
                "unit_count": 11,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.8",
                "product_num_ratings": 36240,
                "product_url": "https://www.amazon.com/dp/B0CV4FQPY1",
                "product_photo": "https://m.media-amazon.com/images/I/81jYzN4cAdL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 15,
                "product_minimum_offer_price": "$21.96",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "50K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0D1XD1ZV3",
                "product_title": "Apple AirPods Pro (2nd Generation) Wireless Ear Buds with USB-C Charging, Up to 2X More Active Noise Cancelling Bluetooth Headphones, Transparency Mode, Adaptive Audio, Personalized Spatial Audio",
                "product_price": "$189.99",
                "product_original_price": "$249.00",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 1351,
                "product_url": "https://www.amazon.com/dp/B0D1XD1ZV3",
                "product_photo": "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 4,
                "product_minimum_offer_price": "$188.09",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 Or fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0D4DJ6BRR",
                "product_title": "DAYBETTER LED Strip Lights 130ft (2 Rolls of 65.6ft), Color Changing Lights Strip for Bedroom, Desk, Indoor, Room Bedroom, Girl Boy Brithday Gifts RGB Decor with Remote and 24V Power Supply",
                "product_price": "$12.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 27499,
                "product_url": "https://www.amazon.com/dp/B0D4DJ6BRR",
                "product_photo": "https://m.media-amazon.com/images/I/813vxzjiChL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$12.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0C9N2L56X",
                "product_title": "The Anxious Generation: How the Great Rewiring of Childhood Is Causing an Epidemic of Mental Illness",
                "product_price": "$0.00",
                "product_original_price": "$20.25",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 1949,
                "product_url": "https://www.amazon.com/dp/B0C9N2L56X",
                "product_photo": "https://m.media-amazon.com/images/I/81N4drWaxuL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Other formats: ",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0D3PBB78P",
                "product_title": "EA SPORTS College Football 25 - PlayStation 5",
                "product_price": "$69.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.com/dp/B0D3PBB78P",
                "product_photo": "https://m.media-amazon.com/images/I/81aE0GBL2mL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$69.99",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Jul 19, 2024",
                "delivery": "FREE deliveryThis item will be released on July 19, 2024.",
                "has_variations": false
            },
            {
                "asin": "B07RFSSYBH",
                "product_title": "Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones",
                "product_price": "$0.00",
                "product_original_price": "$18.00",
                "currency": "USD",
                "product_star_rating": "4.8",
                "product_num_ratings": 129841,
                "product_url": "https://www.amazon.com/dp/B07RFSSYBH",
                "product_photo": "https://m.media-amazon.com/images/I/71F4+7rk2eL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Other formats: ",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0D679Y1WX",
                "product_title": "Passage Du Desir",
                "product_price": "$12.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.com/dp/B0D679Y1WX",
                "product_photo": "https://m.media-amazon.com/images/I/9182719TpgL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 17,
                "product_minimum_offer_price": "$11.61",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "600+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tue, Jul 16",
                "has_variations": false
            },
            {
                "asin": "B0D4GJTYVW",
                "product_title": "Evolve [Prismatic Velvet Tones 2 LP]",
                "product_price": "$34.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "3.4",
                "product_num_ratings": 3,
                "product_url": "https://www.amazon.com/dp/B0D4GJTYVW",
                "product_photo": "https://m.media-amazon.com/images/I/61xdLdVi07L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 16,
                "product_minimum_offer_price": "$31.33",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "1665955430",
                "product_title": "Reckless (The Powerless Trilogy)",
                "product_price": "$14.97",
                "product_original_price": "$21.99",
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 7078,
                "product_url": "https://www.amazon.com/dp/1665955430",
                "product_photo": "https://m.media-amazon.com/images/I/81q6ecxcZUL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$14.97",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "List: ",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0CT2R7199",
                "product_title": "HP DeskJet 2855e Wireless All-in-One Color Inkjet Printer, Scanner, Copier, Best-for-home, 3 months of ink included (588S5A)",
                "product_price": "$49.99",
                "product_original_price": "$84.99",
                "currency": "USD",
                "product_star_rating": "4",
                "product_num_ratings": 47149,
                "product_url": "https://www.amazon.com/dp/B0CT2R7199",
                "product_photo": "https://m.media-amazon.com/images/I/61+biEwB1hL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 12,
                "product_minimum_offer_price": "$47.99",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "30K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 Or fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0D2PKQGQV",
                "product_title": "Hanes Men&#x27;s Pocket Undershirt Pack, Cotton Crew Neck T-Shirt, Moisture Wicking Tee, Assorted 6-Pack",
                "product_price": "$21.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 24889,
                "product_url": "https://www.amazon.com/dp/B0D2PKQGQV",
                "product_photo": "https://m.media-amazon.com/images/I/81v4ewQrCgL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$21.98",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "1K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": true
            },
            {
                "asin": "B0D9BTLD7D",
                "product_title": "Summer in the City: A Novel",
                "product_price": "$14.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.com/dp/B0D9BTLD7D",
                "product_photo": "https://m.media-amazon.com/images/I/61CXLsXznLL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$14.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Other format: ",
                "delivery": "This title will be released on March 25, 2025.",
                "has_variations": false
            },
            {
                "asin": "B0CSYG2CP3",
                "product_title": "Car Carplay Cable for iPhone 15 15 Pro Max 15 Plus Cable, USB A to USB C for Carplay USB C Cord, iPad usb C Cable 10th Gen iPad Pro iPad Air 5th 4th Mini 6th Gen Car Charger Cable Cord Replacement 3FT",
                "product_price": "$8.69",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 726,
                "product_url": "https://www.amazon.com/dp/B0CSYG2CP3",
                "product_photo": "https://m.media-amazon.com/images/I/61fpyOCUDML._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$8.69",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0CTN29L42",
                "product_title": "The Housemaid Is Watching",
                "product_price": "$0.00",
                "product_original_price": "$24.95",
                "currency": "USD",
                "product_star_rating": "4.2",
                "product_num_ratings": 71373,
                "product_url": "https://www.amazon.com/dp/B0CTN29L42",
                "product_photo": "https://m.media-amazon.com/images/I/91SMFFD6MgL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Other formats: ",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0D4TNGLTS",
                "product_title": "Charm",
                "product_price": "$12.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.com/dp/B0D4TNGLTS",
                "product_photo": "https://m.media-amazon.com/images/I/71TRba6lB7L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 17,
                "product_minimum_offer_price": "$12.11",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0CL72PR7B",
                "product_title": "A Death in Cornwall: A Novel (Gabriel Allon Book 24)",
                "product_price": "$15.99",
                "product_original_price": "$32.00",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 1061,
                "product_url": "https://www.amazon.com/dp/B0CL72PR7B",
                "product_photo": "https://m.media-amazon.com/images/I/81KoDl1nhVL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$15.99",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Print List Price: ",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0D1WXVQTN",
                "product_title": "Apple AirPods (3rd Generation) Wireless Ear Buds, Bluetooth Headphones, Personalized Spatial Audio, Sweat and Water Resistant, Lightning Charging Case Included, Up to 30 Hours of Battery Life",
                "product_price": "$139.99",
                "product_original_price": "$169.00",
                "currency": "USD",
                "product_star_rating": "4.2",
                "product_num_ratings": 486,
                "product_url": "https://www.amazon.com/dp/B0D1WXVQTN",
                "product_photo": "https://m.media-amazon.com/images/I/61df2M5+OnL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 3,
                "product_minimum_offer_price": "$138.59",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "10K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 Or fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0CS12LZLS",
                "product_title": "NESCAFÉ Gold Espresso Blonde, Instant Coffee, 3.5 oz",
                "product_price": "$8.59",
                "unit_price": "$2.45",
                "unit_count": 4,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 351,
                "product_url": "https://www.amazon.com/dp/B0CS12LZLS",
                "product_photo": "https://m.media-amazon.com/images/I/71tPLfAANDL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$8.59",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "20K+ bought in past month",
                "delivery": "FREE delivery on $35 shipped by Amazon.",
                "has_variations": false
            },
            {
                "asin": "B0D2JFG16X",
                "product_title": "Ten",
                "product_price": "$13.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "3",
                "product_num_ratings": 2,
                "product_url": "https://www.amazon.com/dp/B0D2JFG16X",
                "product_photo": "https://m.media-amazon.com/images/I/91yG+ehOhGL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$13.98",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "600+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0D5MWVP6C",
                "product_title": "Billy Strings Live Vol. 1",
                "product_price": "$17.49",
                "product_original_price": "$19.98",
                "currency": "USD",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.com/dp/B0D5MWVP6C",
                "product_photo": "https://m.media-amazon.com/images/I/713ggBfzUmL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 15,
                "product_minimum_offer_price": "$17.01",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0CQYH6LQ9",
                "product_title": "8 Pack Refill Cartridge Kit Compatible with ZEVO Plug-in Light M364 and Max, Replacement 100% Fit (8 Refill Cartridges)",
                "product_price": "$17.99",
                "unit_price": "$2.25",
                "unit_count": 8,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.com/dp/B0CQYH6LQ9",
                "product_photo": "https://m.media-amazon.com/images/I/71iEIPz+JSL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$17.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "30K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B09MVCQJBJ",
                "product_title": "Xbox",
                "product_price": "$0.00",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.4",
                "product_num_ratings": 61,
                "product_url": "https://www.amazon.com/dp/B09MVCQJBJ",
                "product_photo": "https://m.media-amazon.com/images/I/41amEfnVeyL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Jul 8, 2024",
                "delivery": "Available instantly on compatible devices",
                "has_variations": false
            },
            {
                "asin": "B0D3PB2DBS",
                "product_title": "EA SPORTS College Football 25 - Xbox Series X",
                "product_price": "$69.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.com/dp/B0D3PB2DBS",
                "product_photo": "https://m.media-amazon.com/images/I/711KlqKMyAL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$69.99",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Jul 19, 2024",
                "delivery": "FREE deliveryThis item will be released on July 19, 2024.",
                "has_variations": false
            },
            {
                "asin": "B0CP93N5S2",
                "product_title": "All the Colors of the Dark",
                "product_price": "$13.99",
                "product_original_price": "$30.00",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 2221,
                "product_url": "https://www.amazon.com/dp/B0CP93N5S2",
                "product_photo": "https://m.media-amazon.com/images/I/81RBcyIyl2L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$13.99",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Print List Price: ",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0D7MC3XH1",
                "product_title": "YOYO School: YOYO Doll School life Dress up",
                "product_price": "$0.00",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "5",
                "product_num_ratings": 4,
                "product_url": "https://www.amazon.com/dp/B0D7MC3XH1",
                "product_photo": "https://m.media-amazon.com/images/I/81m++AruMtL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Jun 20, 2024",
                "delivery": "Available instantly on compatible devices",
                "has_variations": false
            },
            {
                "asin": "B0D73NMM7N",
                "product_title": "Fluvsies Merge Party",
                "product_price": "$0.00",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.1",
                "product_num_ratings": 6,
                "product_url": "https://www.amazon.com/dp/B0D73NMM7N",
                "product_photo": "https://m.media-amazon.com/images/I/81k3RzdCdxL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Jun 27, 2024",
                "delivery": "Available instantly on compatible devices",
                "has_variations": false
            },
            {
                "asin": "B0D7KR99VL",
                "product_title": "Get unlimited Free Robux 2024",
                "product_price": "$0.00",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "2.1",
                "product_num_ratings": 3,
                "product_url": "https://www.amazon.com/dp/B0D7KR99VL",
                "product_photo": "https://m.media-amazon.com/images/I/71H3ahAWJHL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Jun 20, 2024",
                "delivery": "Available instantly on compatible devices",
                "has_variations": false
            },
            {
                "asin": "B0D5J63HJ3",
                "product_title": "Artificial Paradise",
                "product_price": "$13.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.com/dp/B0D5J63HJ3",
                "product_photo": "https://m.media-amazon.com/images/I/61JWlZtBvlL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 16,
                "product_minimum_offer_price": "$13.02",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0CY5H9W4Q",
                "product_title": "Wireless Controller for Switch,Wireless Gamepad Switch Controller Support Motion Control/Dual Vibration（HLD）",
                "product_price": "$27.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.1",
                "product_num_ratings": 96,
                "product_url": "https://www.amazon.com/dp/B0CY5H9W4Q",
                "product_photo": "https://m.media-amazon.com/images/I/51e2yx6fPNL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$27.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0D5WSJCH8",
                "product_title": "Toca Games",
                "product_price": "$0.00",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "5",
                "product_num_ratings": 3,
                "product_url": "https://www.amazon.com/dp/B0D5WSJCH8",
                "product_photo": "https://m.media-amazon.com/images/I/81tWRAHme7L._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Jun 2, 2024",
                "delivery": "Available instantly on compatible devices",
                "has_variations": false
            },
            {
                "asin": "B0CP913K5G",
                "product_title": "Raw Batana Oil for Hair Growth: 100% Pure - Dr. Sebi Batana Oil from Honduras Unrefined Promotes Hair thickness for Men &amp; Women 4.2 OZ…",
                "product_price": "$22.98",
                "unit_price": "$5.48",
                "unit_count": 4,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.3",
                "product_num_ratings": 1617,
                "product_url": "https://www.amazon.com/dp/B0CP913K5G",
                "product_photo": "https://m.media-amazon.com/images/I/41AMizMMADL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$22.98",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "30K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "coupon_text": "Save 20% with coupon",
                "has_variations": false
            },
            {
                "asin": "0140280197",
                "product_title": "The 48 Laws of Power",
                "product_price": "$14.55",
                "product_original_price": "$26.00",
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 78013,
                "product_url": "https://www.amazon.com/dp/0140280197",
                "product_photo": "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 63,
                "product_minimum_offer_price": "$7.77",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "List: ",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "1538742578",
                "product_title": "The Housemaid",
                "product_price": "$6.96",
                "product_original_price": "$12.99",
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 325389,
                "product_url": "https://www.amazon.com/dp/1538742578",
                "product_photo": "https://m.media-amazon.com/images/I/81AHTyq2wVL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 45,
                "product_minimum_offer_price": "$3.41",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "List: ",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0D8MVGNLD",
                "product_title": "The 1974 Live Recordings",
                "product_price": "$129.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": null,
                "product_num_ratings": 0,
                "product_url": "https://www.amazon.com/dp/B0D8MVGNLD",
                "product_photo": "https://m.media-amazon.com/images/I/713ahah+wmL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$129.98",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "2K+ bought in past month",
                "delivery": "FREE delivery Tue, Sep 24 Or fastest delivery Fri, Sep 20 This title will be released on September 20, 2024.",
                "has_variations": false
            },
            {
                "asin": "B0CQMHSPDV",
                "product_title": "Futurebiotics Ashwagandha Extra Strength Stress &amp; Mood Support with BioPerine - Non GMO Formula, 100 Vegetarian Capsules",
                "product_price": "$9.97",
                "unit_price": "$0.10",
                "unit_count": 100,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 2826,
                "product_url": "https://www.amazon.com/dp/B0CQMHSPDV",
                "product_photo": "https://m.media-amazon.com/images/I/7106XKvy7YL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$9.97",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "20K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "coupon_text": "Extra 15% off when you subscribe",
                "has_variations": false
            },
            {
                "asin": "B0D494DNR1",
                "product_title": "Moonag Compatible with Nintendo Switch Controller, Replacement Wireless Controllers with Dual Vibration, Wake-up",
                "product_price": "$28.98",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.8",
                "product_num_ratings": 47,
                "product_url": "https://www.amazon.com/dp/B0D494DNR1",
                "product_photo": "https://m.media-amazon.com/images/I/61SNLbj18AL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$28.98",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0CKNM2RS7",
                "product_title": "Eruption",
                "product_price": "$0.00",
                "product_original_price": "$21.83",
                "currency": "USD",
                "product_star_rating": "4.3",
                "product_num_ratings": 12330,
                "product_url": "https://www.amazon.com/dp/B0CKNM2RS7",
                "product_photo": "https://m.media-amazon.com/images/I/91jZ4396SPL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Other formats: ",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0CTD36YKK",
                "product_title": "Kleenex Ultra Soft Facial Tissues, 8 Cube Boxes, 80 Tissues per Box, 3-Ply, Packaging May Vary",
                "product_price": "$18.99",
                "unit_price": "$2.97",
                "unit_count": 6,
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.7",
                "product_num_ratings": 8298,
                "product_url": "https://www.amazon.com/dp/B0CTD36YKK",
                "product_photo": "https://m.media-amazon.com/images/I/71irzJj3+UL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 5,
                "product_minimum_offer_price": "$18.23",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": true,
                "sales_volume": "40K+ bought in past month",
                "delivery": "FREE delivery Fri, Jul 19 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Jul 15",
                "has_variations": false
            },
            {
                "asin": "B0D7ZPCB25",
                "product_title": "Teacher Simulator: School Days",
                "product_price": "$0.00",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "3",
                "product_num_ratings": 2,
                "product_url": "https://www.amazon.com/dp/B0D7ZPCB25",
                "product_photo": "https://m.media-amazon.com/images/I/51ZPA+MZGgL._AC_UL960_FMwebp_QL65_.png",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$0.00",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Jun 26, 2024",
                "delivery": "Available instantly on compatible devices",
                "has_variations": false
            },
            {
                "asin": "B00OZP5VRS",
                "product_title": "A Court of Thorns and Roses",
                "product_price": "$8.21",
                "product_original_price": "$15.20",
                "currency": "USD",
                "product_star_rating": "4.6",
                "product_num_ratings": 217967,
                "product_url": "https://www.amazon.com/dp/B00OZP5VRS",
                "product_photo": "https://m.media-amazon.com/images/I/81A-T+X6ukL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$8.21",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Digital List Price: ",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0CLKQF5HR",
                "product_title": "Swan Song",
                "product_price": "$14.99",
                "product_original_price": "$30.00",
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 10132,
                "product_url": "https://www.amazon.com/dp/B0CLKQF5HR",
                "product_photo": "https://m.media-amazon.com/images/I/71dSn3QCY6L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$14.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Print List Price: ",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0CL1YQLB5",
                "product_title": "The God of the Woods: A Novel",
                "product_price": "$14.99",
                "product_original_price": null,
                "currency": "USD",
                "product_star_rating": "4.5",
                "product_num_ratings": 656,
                "product_url": "https://www.amazon.com/dp/B0CL1YQLB5",
                "product_photo": "https://m.media-amazon.com/images/I/81WrOo6+IQL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$14.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "Other formats: ",
                "delivery": "Available instantly",
                "has_variations": false
            },
            {
                "asin": "B0D6DVKW1K",
                "product_title": "The Auditorium Vol. 1",
                "product_price": "$12.99",
                "product_original_price": "$13.98",
                "currency": "USD",
                "product_star_rating": "5",
                "product_num_ratings": 2,
                "product_url": "https://www.amazon.com/dp/B0D6DVKW1K",
                "product_photo": "https://m.media-amazon.com/images/I/91avnlK5VOL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$12.99",
                "is_best_seller": false,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE delivery Tue, Aug 27 on $35 of items shipped by AmazonOr fastest delivery Fri, Aug 23 This title will be released on August 23, 2024.",
                "has_variations": false
            },
            {
                "asin": "B0D8J9HYGD",
                "product_title": "Kingdom Of The Planet Of The Apes - UHD/BD Combo + Digital + Steelbook [4K UHD]",
                "product_price": "$34.96",
                "product_original_price": "$65.99",
                "currency": "USD",
                "product_star_rating": "2.6",
                "product_num_ratings": 4,
                "product_url": "https://www.amazon.com/dp/B0D8J9HYGD",
                "product_photo": "https://m.media-amazon.com/images/I/814fq7PUnRL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "$34.96",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "3K+ bought in past month",
                "delivery": "FREE delivery Mon, Sep 2 on $35 of items shipped by AmazonOr fastest delivery Tue, Aug 27 This title will be released on August 27, 2024.",
                "has_variations": false
            }
        ]
    }
}

